name: exploring github actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: check source codes
        uses: actions/checkout@v4
  job2:
    runs-on: ubuntu-latest

    steps:
      - name: practice
        run: echo practice
